### ISSUE TITLE
Fix failing build of HPX 1.9.0 package

### ISSUE THREAD

**Issue by kordejong** [conda-forge/hpx-feedstock#15]
Even though the original PR for the new HPX 1.9.0 package seemed to have succeeded, the build after merging it fails. Anyway, it make sense that it failed. sha256 was wrong, for example.

**Comment by kordejong** [comment]
@hkaiser For some reason HPX 1.9.0 fails to build with Visual Studio. See error message and full log here:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=703918&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=1196

This error pops up after I fixed a typo here (changed `std::` into `hpx::` because `std::construct_at` is a C++20 thing):
https://github.com/STEllAR-GROUP/hpx/blob/ea43d66ac45b3867cd82e96ae7525ec0e39ec7c6/libs/core/datastructures/include/hpx/datastructures/detail/optional.hpp#L350

It is weird that Visual Studio on other people's platforms seems to build 1.9.0 fine, but on this platform it doesn't. I am not a Visual Studio user myself. I checked the log and to me the environment seems fine. VS2019 is used.

Can you maybe have a look at the error message? Is this something you recognize?

**Comment by kordejong** [comment]
@hkaiser I applied the patch, but the result is the same unfortunately:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=703963&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f

**Comment by hkaiser** [comment]
@kordejong what compiler version does your CI use?

**Comment by kordejong** [comment]
@hkaiser I use the default environment that is automatically setup for Conda packages. You can inspect it by looking at the raw log of the build:
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/703963/logs/26
VS2019 is used, but there are more version numbers shown there. I am not sure what "the" compiler version is in the case of Visual Studio. There is also a VS_VERSION=16.0 in the log.

(The scripts for configuring, building and testing HPX 1.9.0 are here: https://github.com/kordejong/hpx-feedstock/tree/gh15/recipe)

**Comment by hkaiser** [comment]
@kordejong thanks, that helped. The following patch should resolve the issue (it resolves it for me):
```
diff --git a/libs/core/schedulers/include/hpx/schedulers/background_scheduler.hpp b/libs/core/schedulers/include/hpx/schedulers/background_scheduler.hpp
index 01f12dc38de..f3c64d8e12e 100644
--- a/libs/core/schedulers/include/hpx/schedulers/background_scheduler.hpp
+++ b/libs/core/schedulers/include/hpx/schedulers/background_scheduler.hpp
@@ -69,9 +69,8 @@ namespace hpx::threads::policies {
             // needs to enable background work
             mode = scheduler_mode(mode & ~scheduler_mode::enable_stealing);
             mode = scheduler_mode(mode & ~scheduler_mode::enable_stealing_numa);
-            mode = scheduler_mode(mode | ~scheduler_mode::do_background_work);
-            mode =
-                scheduler_mode(mode | ~scheduler_mode::do_background_work_only);
+            mode = mode | ~scheduler_mode::do_background_work;
+            mode = mode | ~scheduler_mode::do_background_work_only;
             scheduler_base::set_scheduler_mode(mode);
         }
```

**Comment by kordejong** [comment]
@hkaiser Great, indeed, that helped to get the compiler passed this module. It now struggles with another one, at 65% of the build:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=704036&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f
I noticed that there is already a comment in the code of `when_all_vector.hpp` about MSVC, but maybe the fix is not portable to this version of the compiler.

**Comment by hkaiser** [comment]
> @hkaiser Great, indeed, that helped to get the compiler passed this module. It now struggles with another one, at 65% of the build: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=704036&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f I noticed that there is already a comment in the code of `when_all_vector.hpp` about MSVC, but maybe the fix is not portable to this version of the compiler.

Uhh, this is a real HPX bug in code that is normally not exercised by our CI. Here is another patch:
```
diff --git a/libs/core/execution/include/hpx/execution/algorithms/when_all_vector.hpp b/libs/core/execution/include/hpx/execution/algorithms/when_all_vector.hpp
index 61f2f47dfdd..3e1d5ac934a 100644
--- a/libs/core/execution/include/hpx/execution/algorithms/when_all_vector.hpp
+++ b/libs/core/execution/include/hpx/execution/algorithms/when_all_vector.hpp
@@ -280,7 +280,6 @@ namespace hpx::when_all_vector_detail {
                     op_states[i].template emplace_f<operation_state_type>(
                         hpx::execution::experimental::connect, HPX_MOVE(sender),
                         when_all_vector_receiver{*this, i});
-                    );
 #endif
                     ++i;
                 }
```

**Comment by kordejong** [comment]
@hkaiser Yes, the build succeeds now. I should have noticed the dangling `);` myself. Thanks for your help. I will trigger the build of the new package now.
