### ISSUE TITLE
Port to CMake >= 3.30 (see policy CMP0167)

### ISSUE THREAD

**Issue by kordejong** [conda-forge/hpx-feedstock#33]
Before configuring HPX, patch this CMake script:

```bash
sed -i'' '135 s/MODULE/CONFIG/' $hpx_source_directory/cmake/HPX_SetupBoost.cmake
```

Probably provide a patch file and reference it in `meta.yaml`.

**Comment by hkaiser** [comment]
I think we should apply this to HPX upstream...

**Comment by hkaiser** [comment]
@kordejong see https://github.com/STEllAR-GROUP/hpx/pull/6576

**Comment by kordejong** [comment]
Aha, thanks for heads-up @hkaiser . I am now thinking that I may be able to solve the issue I am seeing with configuring an HPX client project by manipulating the CMake policy stack, setting the `CMP0167` policy to `OLD` locally, when calling `find_package(HPX)`. If that works I will close this issue again. No need to create a patch then, when HPX 1.11 will solve things anyway.
